version: '2'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config-service:
    build: config-service
    ports:
      - 7100:7100

  registry:
    build: registry

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 5000:5000

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  a-service:
    build: a-service
    ports:
      - 5100:5100

  b-service:
    build: b-service
    ports:
      - 5200:5200
  #
  # b-mongodb:
  #   build: mongodb
  #   ports:
  #     - 25200:27017


  # hystrix-dashboard:
  #   build: hystrix-dashboard

  admin-dashboard:
    build: admin-dashboard
