spring.application.name: api-gateway
server.port: 5555

zuul.routes.api-calc.path: /api/calc/**
zuul.routes.api-calc.serviceId: calc-service

zuul.routes.api-net.path: /api/hero/**
zuul.routes.api-net.serviceId: hero

eureka.client.serviceUrl.defaultZone: http://localhost:1111/eureka/