version: '2'

services:
  service2:
    image: kala888/jdk
    volumes:
      - ./:/project
      - ../springboot-startup.sh:/startup.sh
    command: sh -c "/startup.sh springconsul-service2-0.1.0.SNAPSHOT.jar"
    ports:
      - "8180:8080"
    network_mode: "bridge"
