spring.application.name: cfg-service
server.port: 7001
eureka.client.serviceUrl.defaultZone: http://reg-server:1111/eureka/
eureka.instance.prefer-ip-address: true

#Configuration Server

#spring.cloud.config.server.git.uri: https://stash.aaxisgroup.net/users/kalaliu/repos/
#spring.cloud.config.server.git.searchPaths: server-config/browse
#spring.cloud.config.server.git.username: kalaliu
#spring.cloud.config.server.git.password:

spring.cloud.config.server.git.uri: https://github.com/kala888/server-repo
spring.cloud.config.server.git.searchPaths: acp,hero-config
#spring.cloud.config.server.git.searchPaths: acp,scd,hero-config

#server-repo  branch master have two folder acp, scd and hero-config
#file rule: {application}-{profile}.{yml | properties}， label is the git branch
#path rule:
#/{application}/{profile}[/{label}]
#/{application}-{profile}.yml
#/{label}/{application}-{profile}.yml
#/{application}-{profile}.properties
#/{label}/{application}-{profile}.properties

# mapping eg.
#    /acp/prod == /acp/prod/master ==>acp/acp-prod.yml
#    /acp/prod/develop =>acp/acp-prod.yml  from the branch of develop
#    /acp/acp   ==>acp/acp.yml
#    /acp/aaaa ==>acp/acp.yml
#    /hero/dev   ==>hero-config/hero-dev.yml
#    /scd/dev    ==> empty
