version: '2'
services:
  nginx-lb:
    build: nginx/
    mem_limit: 128m
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
    expose:
      - 8000
      - 8443
      - 8001
    restart: always
    command: >
        /bin/containerpilot
        -config file:///etc/containerpilot/containerpilot.json
        nginx -g "daemon off;"
