spring:
  data:
    mongodb:
      host: auth-mongodb
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}
      port: 27017

server.port: 5000
#management.port: 5001
