version: '2'

services:
  db:
    #image: docker.artifactory.aaxischina.net/aaxiscommerce/mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=VCS_DEV
      - MYSQL_USER=vcs_dev_user
      - MYSQL_PASSWORD=passw0rd
    ports:
      - "3306:3306"
    network_mode: "bridge"

  store:
    image: docker.artifactory.aaxischina.net/aaxiscommerce/jboss-wildfly
    ports:
      - "8080:8080"
      - "8787:8787"

    # depends_on:
    #   - db
    volumes:
      - ./:/project
      - ~/.gradle/:/root/.gradle
    links:
       #- db
      - db:db-server
    extra_hosts:
      - "db-server:10.20.20.102"
      - "vcs-mq:10.20.20.101"
      - "vcs-database:10.20.20.101"
    network_mode: "bridge"
